<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>C-BOOST</title>
    <style>
        body {
            color: white;
            background-color: black;
            margin: 0;
            text-align: center;
            padding: 0;
        }
        
        header {
            color: goldenrod;
            text-align: center;
            font-size: large;
            font-weight: bold;
            font-family: arial, sans-serif;
            margin-bottom: 20px;
        }
        
        button {
            margin: 10px;
            padding: 10px 20px;
            cursor: pointer;
            background-color: goldenrod;
            color: white;
            border: none;
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <header>
        <h1>C-BOOST</h1>
    </header>
    <br>
    <img src="boost1.jpg" alt="MTN" style="width:500px; height:400px;" />
    <br>
    <button><a href="community.html" id="community.html" style="margin: 10px;
        padding: 10px 20px;
        cursor: pointer;
        background-color: goldenrod;
        color: white;
        border: none;
        border-radius: 5px;
    ">NEXT</a></button>
    <br><br>
    <footer>
        <p>&copy;2025 C-BOOST</p>
    </footer>
</body>

</html>



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BOOST</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: goldenrod;
            color: white;
        }
        
        form {
            max-width: 400px;
            margin: auto;
            padding: 20px;
            background: goldenrod;
            border-radius: 8px;
            box-shadow: 0 2px 4px white(0, 0, 0, 0.1);
        }
        
        h2 {
            text-align: center;
        }
        
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        
        input,
        textarea,
        button {
            width: 100%;
            margin-bottom: 15px;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        
        button {
            background-color: #25d366;
            color: white;
            border: none;
            cursor: pointer;
        }
        
        button:hover {
            background-color: #1da851;
        }
    </style>
</head>

<body>
    <form id="contactForm">
        <h2>BOOST</h2>

        <label for="name">Name</label>
        <input type="text" id="name" name="name" placeholder="Your Name" required>

        <label for="email">Email</label>
        <input type="email" id="email" name="email" placeholder="Your Email" required>

        <label for="phone">Phone Number</label>
        <input type="tel" id="phone" name="phone" placeholder="Your Phone" required>

        <label for="media">Media</label>
        <input type="text" id="media" name="media" placeholder="TIKTOK,ISTAGRAM,TELEGRAM,YOUTUBE,WHATSAPP,FACEBOOK" required>

        <label for="message">Message</label>
        <textarea id="message" name="message" placeholder="Your Message" rows="5" required></textarea>

        <button type="submit">Send</button>
    </form>
    <br><br>
    <footer style="            text-align: center;">
        <p>&copy;2025 C-BOOST</p>
    </footer>

    <script>
        document.getElementById('contactForm').addEventListener('submit', function(e) {
                    e.preventDefault(); // Prevent the default form submission

                    // Get form values
                    const name = document.getElementById('name').value;
                    const email = document.getElementById('email').value;
                    const phone = document.getElementById('phone').value;
                    const media = document.getElementById('media').value;
                    const message = document.getElementById('message').value;

                    // Your WhatsApp number (Cameroon, including country code)
                    const phoneNumber = "237683199480";

                    // Generate WhatsApp message URL with a specific format
                    const whatsappURL = `https://wa.me/${phoneNumber}?text=${encodeURIComponent(
                `Name: ${name}\nEmail: ${email}\nPhone: ${phone}\nMedia: ${media}\nMessage: ${message}`
            )}`;

            // Redirect user to WhatsApp
            window.open(whatsappURL, '_blank');
        });
    </script>
</body>

</html>
